### ISSUE TITLE
Could not resolve dependencies for project org.eblocker

### ISSUE THREAD

**Issue by johnw230873** [eblocker/eblocker#204] opened 2021-11-29 12:53 UTC
Fresh install of Debian buster
after install ran these commands

su 
apt update
apt install -y openjdk-11-jdk maven redis-server git
sed -i -r 's/^supervised no/supervised systemd/' /etc/redis/redis.conf

export SRC=/home/user/src
mkdir $SRC

git clone https://github.com/eblocker/eblocker-top.git
git clone https://github.com/eblocker/eblocker-crypto.git
git clone https://github.com/eblocker/eblocker-registration-api.git
git clone https://github.com/eblocker/netty-icap.git

cd eblocker-top
mvn install
cd $SRC/eblocker-crypto
mvn install
cd $SRC/eblocker-registration-api
mvn install
cd $SRC/netty-icap
mvn install

cd $SRC
git clone https://github.com/eblocker/eblocker.git
cd eblocker
mvn test

Issue I am having is in the test phase I receive 

[INFO] eBlocker - ICAP-Server ............................. FAILURE [07:07 min]
Could not resolve dependencies for project org.eblocker:eblocker-icapserver:jar:2.9-SNAPSHOT: The following artifacts could not be resolved: org.eblocker:eblocker-crypto:jar:2.8.3, org.eblocker:eblocker-registration-api:jar:2.7.0, org.eblocker:netty-icap:jar:2.1.2: Could not find artifact org.eblocker:eblocker-crypto:jar:2.8.3 in maven.eblocker.org (https://maven.eblocker.org/m2/) 

Any idea on what to try first?

[mnv test -X log.txt](https://github.com/eblocker/eblocker/files/7618292/mnv.test.-X.log.txt)

**Comment by eblosug** [comment] 2021-11-29 15:01
I think the problem is that Maven has cached the information that `eblocker-crypto.jar` etc. are not available from a previous attempt:

    Failure to find org.eblocker:eblocker-crypto:jar:2.8.3 in https://maven.eblocker.org/m2/ was cached in the local repository,
    resolution will not be reattempted until the update interval of maven.eblocker.org has elapsed or updates are forced

You probably have some files ending with `.lastUpdated` below `/root/.m2/repository`.

I think you can force Maven to update the dependencies with the `-U` option.

**Comment by johnw230873** [comment] 2021-11-30 08:20
Cheers, 
I have checked the .m2 folder and there were .lostupdated files but no matter what I try I still haven't been able to build.
Command  **find /root/.m2/repository/ -name *lastUpdated -exec rm -rf {} \;** then mvn test produces the same error

**mvn  package -U produces same error**
**mvn install -U prodcues same error**

 **mvn dependency:purge-local-repository** seems to give the best answer that indicator that it can't find a snapshot.
 I've included this log

[error.txt](https://github.com/eblocker/eblocker/files/7624057/error.txt)

**Comment by eblosug** [comment] 2021-12-01 09:28
Are you sure that the installation of `eblocker-crypto` etc. with `mvn install` worked without error?

These `pom` and `jar` files should be in your local repository:

    ~/.m2/repository/org/eblocker/eblocker-crypto/2.8.3/
                                                        eblocker-crypto-2.8.3.jar
                                                        eblocker-crypto-2.8.3.pom

If not, please run `mvn install` in `eblocker-crypto` etc. again.

**Comment by eblosug** [comment] 2022-05-09 09:28
I assume this issue has been solved, so I close it for now.

There is also a [new document about how to build all packages](https://github.com/eblocker/eblocker-docs/blob/master/BuildPackages.md) from scratch on a Debian Buster system.

**Closed as completed by eblosug** 2022-05-09 09:28 UTC
